name: Lint and test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.2' # The Go version to download (if necessary) and use.
    - name: Vet
      run: go vet ./...
    - name: Build
      run: make build
    - name: Test
      run: make test
